### Авторизация
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=catalog&mode=check_auth
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
###

### Загрузка файлоа
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=catalog&mode=file&filename=v8_B933_661.zip
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: XDEBUG_SESSION=1; PHPSESSID=imq97t68daflie91ceurrvnolrlf84s8;

< E:/OpenServer/domains/zolotoy-telets.loc/_temp/v8_B933_661.zip
###

### Распаковка архива из папки temp/catalog
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=catalog&mode=file&unpacking=true&filename=v8_686E_3573.zip
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: XDEBUG_SESSION=1; PHPSESSID=imq97t68daflie91ceurrvnolrlf84s8;
###


### Импорт категорий
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=catalog&mode=import_categories&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: XDEBUG_SESSION=1; PHPSESSID=imq97t68daflie91ceurrvnolrlf84s8;
###

### Импорт товаров
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=catalog&mode=import_products&filename=import_products.json&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: XDEBUG_SESSION=1; PHPSESSID=imq97t68daflie91ceurrvnolrlf84s8;
###

### Импорт вариантов
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=catalog&mode=import_variants&filename=import_variants.json&update=false
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: XDEBUG_SESSION=1; PHPSESSID=imq97t68daflie91ceurrvnolrlf84s8;
###

### Импорт юзеров
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=users&mode=import&filename=import_users.json
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: XDEBUG_SESSION=1; PHPSESSID=imq97t68daflie91ceurrvnolrlf84s8;
###

### Экспорт юзеров
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=users&mode=export
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: PHPSESSID=6eb6bec554a545c299b440b94164ae00;
###

### Экспорт ордеров
POST http://zolotoy-telets.loc/fivecms/json/1c_exchange.php?type=sales&mode=export&date_begin=2021-01-01
Cache-Control: no-cache
Authorization: Basic YWRtaW46N2RGMjFiakw=
Cookie: PHPSESSID=6eb6bec554a545c299b440b94164ae00;
###
